### ISSUE TITLE
Fix all start.sh scripts

### ISSUE THREAD

**Issue by zvfvrv** [netgroup/rose-srv6-tutorial#20]
we need to fix some problem inside the start.sh scripts, for instance:
https://github.com/netgroup/rose-srv6-tutorial/blob/d05f817c63aac26188e134a382737814873c1e26/nets/8r-1c-in-band-isis/nodeconf/h11/start.sh#L3

**Comment by StefanoSalsano** [comment]
first, we can add new folders for the topologies and separate maintained, in progress and un-maintained topologies:

nets
   | - 8r-1c-out-band-isis

nets-in-progress
   | - 8r-1c-srv6-pm

nets-unmaintained
 |- 3routers 
 |- 8routers 
 |- 8routers-isis-ipv6
 |- 8r-1c-in-band-isis
